### ISSUE TITLE
oci-distribution: authentication from docker.io

### ISSUE THREAD

**Issue by gdesmott** [deislabs/krustlet#597]
Using the same test app from #596 fetching `registry-1.docker.io/mcr.microsoft.com/mcr/hello-world` does not work:

```
RUST_LOG=oci_distribution=trace cargo run --example download-image -- registry-1.docker.io/mcr.microsoft.com/mcr/hello-world
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `/var/home/cassidy/dev/rust/krustlet/target/debug/examples/download-image registry-1.docker.io/mcr.microsoft.com/mcr/hello-world`
[crates/oci-distribution/examples/download-image.rs:11] &reference = registry-1.docker.io/mcr.microsoft.com/mcr/hello-world
[2021-05-12T07:02:22Z DEBUG oci_distribution::client] Pulling image: registry-1.docker.io/mcr.microsoft.com/mcr/hello-world 
[2021-05-12T07:02:22Z DEBUG oci_distribution::client] Authorizing for image: registry-1.docker.io/mcr.microsoft.com/mcr/hello-world 
[2021-05-12T07:02:22Z DEBUG oci_distribution::client] Making authentication call to https://auth.docker.io/token 
[2021-05-12T07:02:22Z DEBUG oci_distribution::client] Received response from auth request: {
     "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK1RDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0U1RVbEdPbEZNUmpRNlEwZFFNenBSTWtWYU9sRklSRUk2VkVkRlZUcFZTRlZNT2taTVZqUTZSMGRXV2pwQk5WUkhPbFJMTkZNNlVVeElTVEFlRncweU1UQXhNalV5TXpFMU1EQmFGdzB5TWpBeE1qVXlNekUxTURCYU1FWXhSREJDQmdOVkJBTVRPMVZQU1ZJNlJFMUpWVHBZVlZKUk9rdFdRVXc2U2twTFZ6cExORkpGT2tWT1RFczZRMWRGVERwRVNrOUlPbEpYTjFjNlRrUktWRHBWV0U1WU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbnZBeVpFK09sZHgrY3hRS0RBWUtmTHJJYk5rK2hnaEg3Ti9mTFpMVDhEYXVPMXRoTWdoamxjcGhFVkNuYTFlMEZpOHVsUlZ4WG1HdWpZVDNXbnFsZ2ZpM2ZYTUQvQlBRTmlkWHZkeWprbDFZS3dPTkl3TkFWMnRXbExxaXFsdGhSWkFnTFdvWWZZMXZQMHFKTFZBbWt5bUkrOXRBcEMxNldNZ1ZFcHJGdE1rNnV0NDlMcDlUR1J0aDJQbHVWc3RSQ1hVUGp4bjI0d3NnYlUwVStjWTJSNEpyZmVJdzN0T1ZKbXNESkNaYW5SNmVheFYyVFZFUkxoZnNGVTlsSHAzcldCZ1RuNVRCSHlMRDNRdGVFLzJ3L3MvcUxZcmdIK1hCMmZBazJPd1NIRG5YWDg4WWVJd0EyVGJJMDdYNS8xQnVsaUwrUDduOWVBT1RmbDkxVlZwNER3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFZUMGxTT2tSTlNWVTZXRlZTVVRwTFZrRk1Pa3BLUzFjNlN6UlNSVHBGVGt4TE9rTlhSVXc2UkVwUFNEcFNWemRYT2s1RVNsUTZWVmhPV0RCR0JnTlZIU01FUHpBOWdEdFNUVWxHT2xGTVJqUTZRMGRRTXpwUk1rVmFPbEZJUkVJNlZFZEZWVHBWU0ZWTU9rWk1WalE2UjBkV1dqcEJOVlJIT2xSTE5GTTZVVXhJU1RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBkN3l1azQrWElabmtQb3RJVkdCeHBRSndpMzQwdExSb3R3Qzl4NkJpdWNDSUhFSmIyWGg0QzhtYVZic1Exd3ZUSCthRGV0VXhBS21lYkdXa3F6Z1J1Z1QiXX0.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE2MjA4MDMyNDIsImlhdCI6MTYyMDgwMjk0MiwiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiI0S0g0NGJVRUE3dHhVUi1NN0g0XyIsIm5iZiI6MTYyMDgwMjY0Miwic3ViIjoiIn0.N53lct-pFSxWL6K38zeRnYfARuXecqWg8-EDjt8qr0FfREihSyg5RyVWpfCkJad2Qba-Lznnw-Dk9Lbnm4Zt6thVT8bL019rfdXwwTQtL9wQmUHK4V85HFlbVie4pqwZ3q8OODdKy4rFCXrIQeQhDlxR1Dj58lMqUct4DufeQcfMpyyFgeqrIisG4NTe4ClEkms0s3cO0PJY_f4auOmVexIaWPe2-8-vHFyGky5i55T3gxdG4ID2MPjT70ypaML5l4t671uFYGKdpVaQR1vhq0SQ_we7VXeyb62fDaRoUJMgShfAlfO2UOpq-wI5viODGXU4qZqXus3nafV3hf5qKQ",
     "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK1RDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0U1RVbEdPbEZNUmpRNlEwZFFNenBSTWtWYU9sRklSRUk2VkVkRlZUcFZTRlZNT2taTVZqUTZSMGRXV2pwQk5WUkhPbFJMTkZNNlVVeElTVEFlRncweU1UQXhNalV5TXpFMU1EQmFGdzB5TWpBeE1qVXlNekUxTURCYU1FWXhSREJDQmdOVkJBTVRPMVZQU1ZJNlJFMUpWVHBZVlZKUk9rdFdRVXc2U2twTFZ6cExORkpGT2tWT1RFczZRMWRGVERwRVNrOUlPbEpYTjFjNlRrUktWRHBWV0U1WU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbnZBeVpFK09sZHgrY3hRS0RBWUtmTHJJYk5rK2hnaEg3Ti9mTFpMVDhEYXVPMXRoTWdoamxjcGhFVkNuYTFlMEZpOHVsUlZ4WG1HdWpZVDNXbnFsZ2ZpM2ZYTUQvQlBRTmlkWHZkeWprbDFZS3dPTkl3TkFWMnRXbExxaXFsdGhSWkFnTFdvWWZZMXZQMHFKTFZBbWt5bUkrOXRBcEMxNldNZ1ZFcHJGdE1rNnV0NDlMcDlUR1J0aDJQbHVWc3RSQ1hVUGp4bjI0d3NnYlUwVStjWTJSNEpyZmVJdzN0T1ZKbXNESkNaYW5SNmVheFYyVFZFUkxoZnNGVTlsSHAzcldCZ1RuNVRCSHlMRDNRdGVFLzJ3L3MvcUxZcmdIK1hCMmZBazJPd1NIRG5YWDg4WWVJd0EyVGJJMDdYNS8xQnVsaUwrUDduOWVBT1RmbDkxVlZwNER3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFZUMGxTT2tSTlNWVTZXRlZTVVRwTFZrRk1Pa3BLUzFjNlN6UlNSVHBGVGt4TE9rTlhSVXc2UkVwUFNEcFNWemRYT2s1RVNsUTZWVmhPV0RCR0JnTlZIU01FUHpBOWdEdFNUVWxHT2xGTVJqUTZRMGRRTXpwUk1rVmFPbEZJUkVJNlZFZEZWVHBWU0ZWTU9rWk1WalE2UjBkV1dqcEJOVlJIT2xSTE5GTTZVVXhJU1RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBkN3l1azQrWElabmtQb3RJVkdCeHBRSndpMzQwdExSb3R3Qzl4NkJpdWNDSUhFSmIyWGg0QzhtYVZic1Exd3ZUSCthRGV0VXhBS21lYkdXa3F6Z1J1Z1QiXX0.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE2MjA4MDMyNDIsImlhdCI6MTYyMDgwMjk0MiwiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiI0S0g0NGJVRUE3dHhVUi1NN0g0XyIsIm5iZiI6MTYyMDgwMjY0Miwic3ViIjoiIn0.N53lct-pFSxWL6K38zeRnYfARuXecqWg8-EDjt8qr0FfREihSyg5RyVWpfCkJad2Qba-Lznnw-Dk9Lbnm4Zt6thVT8bL019rfdXwwTQtL9wQmUHK4V85HFlbVie4pqwZ3q8OODdKy4rFCXrIQeQhDlxR1Dj58lMqUct4DufeQcfMpyyFgeqrIisG4NTe4ClEkms0s3cO0PJY_f4auOmVexIaWPe2-8-vHFyGky5i55T3gxdG4ID2MPjT70ypaML5l4t671uFYGKdpVaQR1vhq0SQ_we7VXeyb62fDaRoUJMgShfAlfO2UOpq-wI5viODGXU4qZqXus3nafV3hf5qKQ",
     "expires_in": 300,
     "issued_at": "2021-05-12T07:02:22.852326643Z"
    } 
[2021-05-12T07:02:22Z DEBUG oci_distribution::client] Succesfully authorized for image 'registry-1.docker.io/mcr.microsoft.com/mcr/hello-world' 
[2021-05-12T07:02:22Z DEBUG oci_distribution::client] Pulling image manifest from https://registry-1.docker.io/v2/mcr.microsoft.com/mcr/hello-world/manifests/latest 
Error: OCI API error: authentication required on https://registry-1.docker.io/v2/mcr.microsoft.com/mcr/hello-world/manifests/latest
```

It's strange because fetching `registry-1.docker.io/library/hello-world:latest` does not hit this error:

```
$ RUST_LOG=oci_distribution=trace cargo run --example download-image -- registry-1.docker.io/library/hello-world:latest
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `/var/home/cassidy/dev/rust/krustlet/target/debug/examples/download-image 'registry-1.docker.io/library/hello-world:latest'`
[crates/oci-distribution/examples/download-image.rs:11] &reference = registry-1.docker.io/library/hello-world:latest
[2021-05-12T07:05:17Z DEBUG oci_distribution::client] Pulling image: registry-1.docker.io/library/hello-world:latest 
[2021-05-12T07:05:17Z DEBUG oci_distribution::client] Authorizing for image: registry-1.docker.io/library/hello-world:latest 
[2021-05-12T07:05:17Z DEBUG oci_distribution::client] Making authentication call to https://auth.docker.io/token 
[2021-05-12T07:05:18Z DEBUG oci_distribution::client] Received response from auth request: {
     "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK1RDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0U1RVbEdPbEZNUmpRNlEwZFFNenBSTWtWYU9sRklSRUk2VkVkRlZUcFZTRlZNT2taTVZqUTZSMGRXV2pwQk5WUkhPbFJMTkZNNlVVeElTVEFlRncweU1UQXhNalV5TXpFMU1EQmFGdzB5TWpBeE1qVXlNekUxTURCYU1FWXhSREJDQmdOVkJBTVRPMVZQU1ZJNlJFMUpWVHBZVlZKUk9rdFdRVXc2U2twTFZ6cExORkpGT2tWT1RFczZRMWRGVERwRVNrOUlPbEpYTjFjNlRrUktWRHBWV0U1WU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbnZBeVpFK09sZHgrY3hRS0RBWUtmTHJJYk5rK2hnaEg3Ti9mTFpMVDhEYXVPMXRoTWdoamxjcGhFVkNuYTFlMEZpOHVsUlZ4WG1HdWpZVDNXbnFsZ2ZpM2ZYTUQvQlBRTmlkWHZkeWprbDFZS3dPTkl3TkFWMnRXbExxaXFsdGhSWkFnTFdvWWZZMXZQMHFKTFZBbWt5bUkrOXRBcEMxNldNZ1ZFcHJGdE1rNnV0NDlMcDlUR1J0aDJQbHVWc3RSQ1hVUGp4bjI0d3NnYlUwVStjWTJSNEpyZmVJdzN0T1ZKbXNESkNaYW5SNmVheFYyVFZFUkxoZnNGVTlsSHAzcldCZ1RuNVRCSHlMRDNRdGVFLzJ3L3MvcUxZcmdIK1hCMmZBazJPd1NIRG5YWDg4WWVJd0EyVGJJMDdYNS8xQnVsaUwrUDduOWVBT1RmbDkxVlZwNER3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFZUMGxTT2tSTlNWVTZXRlZTVVRwTFZrRk1Pa3BLUzFjNlN6UlNSVHBGVGt4TE9rTlhSVXc2UkVwUFNEcFNWemRYT2s1RVNsUTZWVmhPV0RCR0JnTlZIU01FUHpBOWdEdFNUVWxHT2xGTVJqUTZRMGRRTXpwUk1rVmFPbEZJUkVJNlZFZEZWVHBWU0ZWTU9rWk1WalE2UjBkV1dqcEJOVlJIT2xSTE5GTTZVVXhJU1RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBkN3l1azQrWElabmtQb3RJVkdCeHBRSndpMzQwdExSb3R3Qzl4NkJpdWNDSUhFSmIyWGg0QzhtYVZic1Exd3ZUSCthRGV0VXhBS21lYkdXa3F6Z1J1Z1QiXX0.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6ImxpYnJhcnkvaGVsbG8td29ybGQiLCJhY3Rpb25zIjpbInB1bGwiXSwicGFyYW1ldGVycyI6eyJwdWxsX2xpbWl0IjoiMTAwIiwicHVsbF9saW1pdF9pbnRlcnZhbCI6IjIxNjAwIn19XSwiYXVkIjoicmVnaXN0cnkuZG9ja2VyLmlvIiwiZXhwIjoxNjIwODAzNDE4LCJpYXQiOjE2MjA4MDMxMTgsImlzcyI6ImF1dGguZG9ja2VyLmlvIiwianRpIjoib2VRVmJWQVh2X1BBUFVCU1Fpc1kiLCJuYmYiOjE2MjA4MDI4MTgsInN1YiI6IiJ9.bKb_1XVhe2xO7sBL5-SiypviejnjCPtLzqvhenrHa325FttTtJ1j9ZaOiplV_jCq6nowd8vltgzKdsvLvrKvfnm0z9scv0nqfdoexWKQd59tmOQj4JTPlPu7YeWAnZbYV6o1QHOjKur0qclXuX641iOCOBoSNerMtWzXXN18tL9P0pNhYUX0YTPZkou0geJDTRN_Mw3MuTyjBzbyARNZuXuBWt2PVh01the5qh0tS5E0QU6NwZf02tbzcNQIUgQY-gGqSDnP6k2EJNjFlm1hgyQCIcVhPoJczXikhuxAPTA26QYzTGn3z-P2Zw7BSeNiWv7geE0UWQzJ22MUBNVhGg",
     "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK1RDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0U1RVbEdPbEZNUmpRNlEwZFFNenBSTWtWYU9sRklSRUk2VkVkRlZUcFZTRlZNT2taTVZqUTZSMGRXV2pwQk5WUkhPbFJMTkZNNlVVeElTVEFlRncweU1UQXhNalV5TXpFMU1EQmFGdzB5TWpBeE1qVXlNekUxTURCYU1FWXhSREJDQmdOVkJBTVRPMVZQU1ZJNlJFMUpWVHBZVlZKUk9rdFdRVXc2U2twTFZ6cExORkpGT2tWT1RFczZRMWRGVERwRVNrOUlPbEpYTjFjNlRrUktWRHBWV0U1WU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbnZBeVpFK09sZHgrY3hRS0RBWUtmTHJJYk5rK2hnaEg3Ti9mTFpMVDhEYXVPMXRoTWdoamxjcGhFVkNuYTFlMEZpOHVsUlZ4WG1HdWpZVDNXbnFsZ2ZpM2ZYTUQvQlBRTmlkWHZkeWprbDFZS3dPTkl3TkFWMnRXbExxaXFsdGhSWkFnTFdvWWZZMXZQMHFKTFZBbWt5bUkrOXRBcEMxNldNZ1ZFcHJGdE1rNnV0NDlMcDlUR1J0aDJQbHVWc3RSQ1hVUGp4bjI0d3NnYlUwVStjWTJSNEpyZmVJdzN0T1ZKbXNESkNaYW5SNmVheFYyVFZFUkxoZnNGVTlsSHAzcldCZ1RuNVRCSHlMRDNRdGVFLzJ3L3MvcUxZcmdIK1hCMmZBazJPd1NIRG5YWDg4WWVJd0EyVGJJMDdYNS8xQnVsaUwrUDduOWVBT1RmbDkxVlZwNER3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFZUMGxTT2tSTlNWVTZXRlZTVVRwTFZrRk1Pa3BLUzFjNlN6UlNSVHBGVGt4TE9rTlhSVXc2UkVwUFNEcFNWemRYT2s1RVNsUTZWVmhPV0RCR0JnTlZIU01FUHpBOWdEdFNUVWxHT2xGTVJqUTZRMGRRTXpwUk1rVmFPbEZJUkVJNlZFZEZWVHBWU0ZWTU9rWk1WalE2UjBkV1dqcEJOVlJIT2xSTE5GTTZVVXhJU1RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBkN3l1azQrWElabmtQb3RJVkdCeHBRSndpMzQwdExSb3R3Qzl4NkJpdWNDSUhFSmIyWGg0QzhtYVZic1Exd3ZUSCthRGV0VXhBS21lYkdXa3F6Z1J1Z1QiXX0.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6ImxpYnJhcnkvaGVsbG8td29ybGQiLCJhY3Rpb25zIjpbInB1bGwiXSwicGFyYW1ldGVycyI6eyJwdWxsX2xpbWl0IjoiMTAwIiwicHVsbF9saW1pdF9pbnRlcnZhbCI6IjIxNjAwIn19XSwiYXVkIjoicmVnaXN0cnkuZG9ja2VyLmlvIiwiZXhwIjoxNjIwODAzNDE4LCJpYXQiOjE2MjA4MDMxMTgsImlzcyI6ImF1dGguZG9ja2VyLmlvIiwianRpIjoib2VRVmJWQVh2X1BBUFVCU1Fpc1kiLCJuYmYiOjE2MjA4MDI4MTgsInN1YiI6IiJ9.bKb_1XVhe2xO7sBL5-SiypviejnjCPtLzqvhenrHa325FttTtJ1j9ZaOiplV_jCq6nowd8vltgzKdsvLvrKvfnm0z9scv0nqfdoexWKQd59tmOQj4JTPlPu7YeWAnZbYV6o1QHOjKur0qclXuX641iOCOBoSNerMtWzXXN18tL9P0pNhYUX0YTPZkou0geJDTRN_Mw3MuTyjBzbyARNZuXuBWt2PVh01the5qh0tS5E0QU6NwZf02tbzcNQIUgQY-gGqSDnP6k2EJNjFlm1hgyQCIcVhPoJczXikhuxAPTA26QYzTGn3z-P2Zw7BSeNiWv7geE0UWQzJ22MUBNVhGg",
     "expires_in": 300,
     "issued_at": "2021-05-12T07:05:18.189899137Z"
    } 
[2021-05-12T07:05:18Z DEBUG oci_distribution::client] Succesfully authorized for image 'registry-1.docker.io/library/hello-world:latest' 
[2021-05-12T07:05:18Z DEBUG oci_distribution::client] Pulling image manifest from https://registry-1.docker.io/v2/library/hello-world/manifests/latest 
[2021-05-12T07:05:18Z DEBUG oci_distribution::client] validating manifest: {"manifests":[{"digest":"sha256:1b26826f602946860c279fce658f31050cff2c596583af237d971f4629b57792","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"amd64","os":"linux"},"size":525},{"digest":"sha256:e5785cb0c62cebbed4965129bae371f0589cadd6d84798fb58c2c5f9e237efd9","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"arm","os":"linux","variant":"v5"},"size":525},{"digest":"sha256:50b8560ad574c779908da71f7ce370c0a2471c098d44d1c8f6b513c5a55eeeb1","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"arm","os":"linux","variant":"v7"},"size":525},{"digest":"sha256:963612c5503f3f1674f315c67089dee577d8cc6afc18565e0b4183ae355fb343","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"arm64","os":"linux","variant":"v8"},"size":525},{"digest":"sha256:cb55d8f7347376e1ba38ca740904b43c9a52f66c7d2ae1ef1a0de1bc9f40df98","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"386","os":"linux"},"size":525},{"digest":"sha256:88b2e00179bd6c4064612403c8d42a13de7ca809d61fee966ce9e129860a8a90","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"mips64le","os":"linux"},"size":525},{"digest":"sha256:bb7ab0fa94fdd78aca84b27a1bd46c4b811051f9b69905d81f5f267fc6546a9d","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"ppc64le","os":"linux"},"size":525},{"digest":"sha256:e49abad529e5d9bd6787f3abeab94e09ba274fe34731349556a850b9aebbf7bf","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"s390x","os":"linux"},"size":525},{"digest":"sha256:ea0cfb27fd41ea0405d3095880c1efa45710f5bcdddb7d7d5a7317ad4825ae14","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"amd64","os":"windows","os.version":"10.0.17763.1879"},"size":1125}],"mediaType":"application\/vnd.docker.distribution.manifest.list.v2+json","schemaVersion":2} 
Error: unsupported media type: application/vnd.docker.distribution.manifest.list.v2+json
```

**Comment by bacongobbler** [comment]
is this fixed with #606 or is there something else we need to handle to accommodate this?

**Comment by bacongobbler** [comment]
Hmm... It might be due to this block of code, actually:

https://github.com/deislabs/krustlet/blob/e57d51cf3faaafaefd95c1b126c496457c32ce70/crates/oci-distribution/src/client.rs#L417

The token registry might not contain the same name. Can you check and confirm?

**Comment by radu-matei** [comment]
Not sure if this is related, but I _think_ you are no longer able to pull images from MCR through Docker Hub - https://techcommunity.microsoft.com/t5/azure-developer-community-blog/deprecating-the-distribution-of-microsoft-container-images-via/bc-p/2371104

**Comment by gdesmott** [comment]
> is this fixed with #606 or is there something else we need to handle to accommodate this?

That still does not work:

```
$ RUST_LOG=oci_distribution=trace cargo run --example download-image -- registry-1.docker.io/mcr.microsoft.com/mcr/hello-world
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `/var/home/cassidy/dev/rust/krustlet/target/debug/examples/download-image registry-1.docker.io/mcr.microsoft.com/mcr/hello-world`
[crates/oci-distribution/examples/download-image.rs:11] &reference = registry-1.docker.io/mcr.microsoft.com/mcr/hello-world
[2021-06-09T08:30:31Z DEBUG oci_distribution::client] Pulling image: registry-1.docker.io/mcr.microsoft.com/mcr/hello-world 
[2021-06-09T08:30:31Z DEBUG oci_distribution::client] Authorizing for image: registry-1.docker.io/mcr.microsoft.com/mcr/hello-world 
[2021-06-09T08:30:31Z DEBUG oci_distribution::client] Making authentication call to https://auth.docker.io/token 
[2021-06-09T08:30:32Z DEBUG oci_distribution::client] Received response from auth request: {
     "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK1RDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0U1RVbEdPbEZNUmpRNlEwZFFNenBSTWtWYU9sRklSRUk2VkVkRlZUcFZTRlZNT2taTVZqUTZSMGRXV2pwQk5WUkhPbFJMTkZNNlVVeElTVEFlRncweU1UQXhNalV5TXpFMU1EQmFGdzB5TWpBeE1qVXlNekUxTURCYU1FWXhSREJDQmdOVkJBTVRPMVZQU1ZJNlJFMUpWVHBZVlZKUk9rdFdRVXc2U2twTFZ6cExORkpGT2tWT1RFczZRMWRGVERwRVNrOUlPbEpYTjFjNlRrUktWRHBWV0U1WU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbnZBeVpFK09sZHgrY3hRS0RBWUtmTHJJYk5rK2hnaEg3Ti9mTFpMVDhEYXVPMXRoTWdoamxjcGhFVkNuYTFlMEZpOHVsUlZ4WG1HdWpZVDNXbnFsZ2ZpM2ZYTUQvQlBRTmlkWHZkeWprbDFZS3dPTkl3TkFWMnRXbExxaXFsdGhSWkFnTFdvWWZZMXZQMHFKTFZBbWt5bUkrOXRBcEMxNldNZ1ZFcHJGdE1rNnV0NDlMcDlUR1J0aDJQbHVWc3RSQ1hVUGp4bjI0d3NnYlUwVStjWTJSNEpyZmVJdzN0T1ZKbXNESkNaYW5SNmVheFYyVFZFUkxoZnNGVTlsSHAzcldCZ1RuNVRCSHlMRDNRdGVFLzJ3L3MvcUxZcmdIK1hCMmZBazJPd1NIRG5YWDg4WWVJd0EyVGJJMDdYNS8xQnVsaUwrUDduOWVBT1RmbDkxVlZwNER3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFZUMGxTT2tSTlNWVTZXRlZTVVRwTFZrRk1Pa3BLUzFjNlN6UlNSVHBGVGt4TE9rTlhSVXc2UkVwUFNEcFNWemRYT2s1RVNsUTZWVmhPV0RCR0JnTlZIU01FUHpBOWdEdFNUVWxHT2xGTVJqUTZRMGRRTXpwUk1rVmFPbEZJUkVJNlZFZEZWVHBWU0ZWTU9rWk1WalE2UjBkV1dqcEJOVlJIT2xSTE5GTTZVVXhJU1RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBkN3l1azQrWElabmtQb3RJVkdCeHBRSndpMzQwdExSb3R3Qzl4NkJpdWNDSUhFSmIyWGg0QzhtYVZic1Exd3ZUSCthRGV0VXhBS21lYkdXa3F6Z1J1Z1QiXX0.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE2MjMyMjc3MzIsImlhdCI6MTYyMzIyNzQzMiwiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiIyRV9FaTBfOEllQzZIRkd3QjZaUiIsIm5iZiI6MTYyMzIyNzEzMiwic3ViIjoiIn0.nEAp6s-rg6Me2Yc1aVPgPF3XwUbIzPgokWsyESwl_pWdZLw9SIDUJMH7FTfQfSkBXaDpkZXBU2q07avuHx2HwQ1hszvSI6kTHAFUHxLZR0LSh4-VwdlkWdKfF5zCifpc3w1DNl1g0e_SKseFSWBa_q5Vg7NtTv_97W-SkuUCOeWB1qDg311LfMdnMu9DydVBA6mnL5fC6OeGV_NdXN8_I0Sd-QWq8s-Ak68e7RhKeeSevL99C4clF1DFZi11ez_digZHL792EkLpSmzr-Sr-GEEG39PN99ahPZZBo76wX3WTtlqPvY7oiQcqdHDC9iVelxWNghbXSVWzIsscuc0LVA",
     "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK1RDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0U1RVbEdPbEZNUmpRNlEwZFFNenBSTWtWYU9sRklSRUk2VkVkRlZUcFZTRlZNT2taTVZqUTZSMGRXV2pwQk5WUkhPbFJMTkZNNlVVeElTVEFlRncweU1UQXhNalV5TXpFMU1EQmFGdzB5TWpBeE1qVXlNekUxTURCYU1FWXhSREJDQmdOVkJBTVRPMVZQU1ZJNlJFMUpWVHBZVlZKUk9rdFdRVXc2U2twTFZ6cExORkpGT2tWT1RFczZRMWRGVERwRVNrOUlPbEpYTjFjNlRrUktWRHBWV0U1WU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbnZBeVpFK09sZHgrY3hRS0RBWUtmTHJJYk5rK2hnaEg3Ti9mTFpMVDhEYXVPMXRoTWdoamxjcGhFVkNuYTFlMEZpOHVsUlZ4WG1HdWpZVDNXbnFsZ2ZpM2ZYTUQvQlBRTmlkWHZkeWprbDFZS3dPTkl3TkFWMnRXbExxaXFsdGhSWkFnTFdvWWZZMXZQMHFKTFZBbWt5bUkrOXRBcEMxNldNZ1ZFcHJGdE1rNnV0NDlMcDlUR1J0aDJQbHVWc3RSQ1hVUGp4bjI0d3NnYlUwVStjWTJSNEpyZmVJdzN0T1ZKbXNESkNaYW5SNmVheFYyVFZFUkxoZnNGVTlsSHAzcldCZ1RuNVRCSHlMRDNRdGVFLzJ3L3MvcUxZcmdIK1hCMmZBazJPd1NIRG5YWDg4WWVJd0EyVGJJMDdYNS8xQnVsaUwrUDduOWVBT1RmbDkxVlZwNER3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFZUMGxTT2tSTlNWVTZXRlZTVVRwTFZrRk1Pa3BLUzFjNlN6UlNSVHBGVGt4TE9rTlhSVXc2UkVwUFNEcFNWemRYT2s1RVNsUTZWVmhPV0RCR0JnTlZIU01FUHpBOWdEdFNUVWxHT2xGTVJqUTZRMGRRTXpwUk1rVmFPbEZJUkVJNlZFZEZWVHBWU0ZWTU9rWk1WalE2UjBkV1dqcEJOVlJIT2xSTE5GTTZVVXhJU1RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBkN3l1azQrWElabmtQb3RJVkdCeHBRSndpMzQwdExSb3R3Qzl4NkJpdWNDSUhFSmIyWGg0QzhtYVZic1Exd3ZUSCthRGV0VXhBS21lYkdXa3F6Z1J1Z1QiXX0.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE2MjMyMjc3MzIsImlhdCI6MTYyMzIyNzQzMiwiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiIyRV9FaTBfOEllQzZIRkd3QjZaUiIsIm5iZiI6MTYyMzIyNzEzMiwic3ViIjoiIn0.nEAp6s-rg6Me2Yc1aVPgPF3XwUbIzPgokWsyESwl_pWdZLw9SIDUJMH7FTfQfSkBXaDpkZXBU2q07avuHx2HwQ1hszvSI6kTHAFUHxLZR0LSh4-VwdlkWdKfF5zCifpc3w1DNl1g0e_SKseFSWBa_q5Vg7NtTv_97W-SkuUCOeWB1qDg311LfMdnMu9DydVBA6mnL5fC6OeGV_NdXN8_I0Sd-QWq8s-Ak68e7RhKeeSevL99C4clF1DFZi11ez_digZHL792EkLpSmzr-Sr-GEEG39PN99ahPZZBo76wX3WTtlqPvY7oiQcqdHDC9iVelxWNghbXSVWzIsscuc0LVA",
     "expires_in": 300,
     "issued_at": "2021-06-09T08:30:32.204944662Z"
    } 
[2021-06-09T08:30:32Z DEBUG oci_distribution::client] Succesfully authorized for image 'registry-1.docker.io/mcr.microsoft.com/mcr/hello-world' 
[2021-06-09T08:30:32Z DEBUG oci_distribution::client] Pulling image manifest from https://registry-1.docker.io/v2/mcr.microsoft.com/mcr/hello-world/manifests/latest 
Error: OCI API error: authentication required on https://registry-1.docker.io/v2/mcr.microsoft.com/mcr/hello-world/manifests/latest
```
> Hmm... It might be due to this block of code, actually:
> 
> https://github.com/deislabs/krustlet/blob/e57d51cf3faaafaefd95c1b126c496457c32ce70/crates/oci-distribution/src/client.rs#L417
> 
> The token registry might not contain the same name. Can you check and confirm?

This code path does not seem to be called.
You can easily test using this branch: https://github.com/gdesmott/krustlet/tree/download-image

> That being said, it also looks like you are trying to pull container images, and as the second error points out, that is not supported yet.

Yeah I know, trying to tackle issues one by one. :)
